spring:
  datasource:
    url: jdbc:h2:mem:rollcrew
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: rollcrew-secret-key-must-be-at-least-32-characters-long
  expiration: 86400000